language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: BvG1h30qMfhRBIzV4Cm9RkgsaOivkWoLKetmHWh/unJOitzceHOJFoiz1hEiyyIhbhunt6z6QhHjL3DoWc3b9bpXV1Oawfx1FIQheLluGymlpEqqY94iRoS9HRF6jCrL8S+XCesXxwnDt3Aasdw4yTb6Orz+z88cM4/iFuhI3QVfSAfPV+neWEQyOKVsu0DbEWwkcmWQMP9dRQS4UVyLaMhn0W1NG9J5/bqaBNxH3oT+A/Ew++SbIQKEQ3Rs6HCS5fPUQAVczbahyYtXTPxc4Ssopq7ZL4faCVMNUF5cdaXvC4BFQZWfkGJa7CJPxC514fNZCEe0k12r5eDWiBp7JxIfuPJSn44nl0QmYkCzg1/KxpZWo3g3YpMWAPdsHN1PwKI9KiHdxfEPyO77LLPTvkKIcZb5bL0kFr5YKc9xUJwT0qIKr2vqT53nX7WSBwpstRy8jvOfiryaVhTKF8ffZjJmtn53holOaiu21gd1IdIqRK1gQmAc764kQacH6w72VdQksSeURsjzhUMLVTyRj1Iqyl2rdX14L+4fMwpQIsRy/3yFeDv1QybXVNRMpQcxTtbqA0Awx6XHF5vfBoI3GIkzqIW16zp2wuhmOz4iBXXNDcJVhSO7PQQKYEkS+xbGAHTo6LusCsmHkoxStHPTqWBcwaOrjMpDGNL367qcJbA=
  on:
    tags: true
    repo: sjoerdk/fileselection
    python: 3.6
